#!/bin/bash

ISCSIADM=/sbin/iscsiadm

UUID_FILE=$1

PORTAL_IP=134.158.75.2
PORTAL_PORT=3260
PORTAL="$PORTAL_IP:$PORTAL_PORT"

DISK=`cat $UUID_FILE`
DETACH_CMD="$ISCSIADM --mode node --portal $PORTAL --targetname $DISK --logout"
echo $DETACH_CMD
$DETACH_CMD
